# Generated by Django 4.2.14 on 2024-07-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('current_action', models.CharField(blank=True, max_length=200)),
                ('gauge', models.IntegerField(default=0)),
                ('final_action', models.TextField(blank=True)),
            ],
        ),
    ]
