# Generated by Django 4.2.14 on 2024-07-22 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('current_action', models.CharField(blank=True, max_length=200)),
                ('gauge', models.IntegerField(default=0)),
                ('final_action', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('weather', models.CharField(choices=[('sunny', '맑음'), ('partly_cloudy', '약간 흐림'), ('cloudy', '흐림'), ('rain', '비'), ('snow', '눈')], max_length=20)),
                ('wake_up_time', models.TimeField()),
                ('sleep_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
