# Generated by Django 4.2.14 on 2024-07-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='age',
        ),
        migrations.RemoveField(
            model_name='character',
            name='current_action',
        ),
        migrations.RemoveField(
            model_name='character',
            name='final_action',
        ),
        migrations.RemoveField(
            model_name='character',
            name='gauge',
        ),
        migrations.RemoveField(
            model_name='character',
            name='gender',
        ),
        migrations.AddField(
            model_name='character',
            name='character_type',
            field=models.CharField(blank=True, choices=[('dol', '돌고래'), ('ang', '앵무새'), ('da', '다람쥐')], max_length=100, null=True),
        ),
    ]
