# Generated by Django 4.2.14 on 2024-07-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='final_action',
            field=models.TextField(blank=True),
        ),
    ]
