# Generated by Django 4.2.14 on 2024-07-23 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('character', '0003_character_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('journal_entries', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('action_type', models.CharField(choices=[('eat', '먹기'), ('wash', '씻기'), ('walk', '산책하기'), ('shower', '샤워하기')], max_length=10)),
                ('meal_time', models.CharField(blank=True, choices=[('breakfast', '아침'), ('lunch', '점심'), ('dinner', '저녁'), ('snack', '간식')], max_length=10, null=True)),
                ('action_detail', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='character_type',
        ),
        migrations.AddField(
            model_name='character',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='character',
            name='gauge',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='type',
            field=models.CharField(choices=[('parrot', '앵무새'), ('dolphin', '돌고래'), ('squirrel', '다람쥐')], default='parrot', max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Diary',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character'),
        ),
        migrations.AddField(
            model_name='ending',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.character'),
        ),
    ]
