# Generated by Django 4.2.14 on 2024-07-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_ending_journalentry_remove_character_character_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='action_type',
            field=models.CharField(choices=[('eat', '먹기'), ('wash', '씻기'), ('walk', '산책하기'), ('clean', '청소하기')], max_length=10),
        ),
    ]
