# Generated by Django 4.2.14 on 2024-07-25 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ending',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='action_type',
            field=models.CharField(choices=[('eat', '먹기'), ('wash', '씻기'), ('walk', '산책하기'), ('cleaning', '청소하기')], max_length=10),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
