# Generated by Django 4.2.14 on 2024-07-24 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_everylist_user_alter_lifelist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='everylist',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='everylist',
            name='due_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='lifelist',
            name='target_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='lifelist',
            name='target_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
